### ISSUE TITLE
Hard to determine which node was clicked

### ISSUE THREAD

**Issue by ghost** [gribouille/elm-treeview#5]
I'm trying to use this package to implement a tree of values that are lazily loaded over HTTP, so I need to know when a specific node is clicked so a request can be sent off. It would be great if you could pass in a `msg` to the node that the tree would then embed, I'm just not sure how that would work with the current architecture.

Is there a recommended way to resolve which node was clicked by the user?

**Comment by gribouille** [comment]
`Treeview.Msg` contains the event type and the key. For example, to trace the selected node id in the example 4:

```elm
update : Msg -> Model -> Model
update msg model =
  case msg of
    OnTreeview msgTreeview -> 
      let 
        _ = Debug.log "=> " (debug msgTreeview) 
      in 
        Treeview.update msgTreeview model
    ToggleAll -> Treeview.toggleAll model


debug : Treeview.Msg -> String
debug m =
  case m of 
    Treeview.Toggle k -> "toggle: " ++ k
    Treeview.Select k -> "select: " ++ k
    Treeview.Search s -> "search: " ++ s 
    Treeview.ToggleCheck _ _ k _ -> "toggle check: " ++ k
```
